events {}

http {
    include /etc/nginx/mime.types;
    sendfile on;

    server {
        listen 3090;

        location / {
            alias /usr/share/nginx/html/;
            index index.html;
            try_files $uri $uri/ /index.html;
        }
    }
}
